id: I7BB59996
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:42:39+00:00'
last_modified: '2022-06-08T06:32:15.163527+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18536
  title: ཤ་ཆང་ཐ་མ་ཁ་སོགས་ཀྱི་ཉེས་དམིགས་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5F84:
      image_group_id: I1KG18557
      title: ''
      total_pages: 330
      order: 1
      base_file: 5F84.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
