id: P006742
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18536
  title: ཤ་ཆང་ཐ་མ་ཁ་སོགས་ཀྱི་ཉེས་དམིགས་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    4b8ac1a8d2b84bb8b596bd3b440883d7:
      image_group_id: I1KG18557
      title: ''
      volume_number: 1
      total_pages: 330
      base_file: v001.txt
